### ISSUE TITLE
[Compatibility Request] Call releaseEntity from block, not item

### ISSUE THREAD

**Issue by skyjay1** [Quintinity/MobCages#7]
I suggest calling TileEntityCage#releaseEntity from the block instead of making a custom item.
This would help for several reasons:
- You can release the mobs by using any specified item
- \- - By hardcoding items and / or using OreDictionary to find items that match "wrench"
- You don't have to make a custom crowbar thing that you'll only use every few days anyway

This would be done by overriding onBlockActivated:
`public boolean onBlockActivated(World worldIn, int x, int y, int z, EntityPlayer player, int side, float hitX, float hitY, float hitZ)`

I would make a pull request for this, but I don't remember all the oredict methods from 1.7.10.

**Comment by vladmarica** [comment]
I am going to add this, but after doing some research, I have come to some conclusions:
- I cannot use the ore dictionary because it is intended for 'dumb' items only, like ingots and planks, not for complex items with logic like wrenches. For this reason, mod developers do not register wrenches in the ore dict.
- Lots of mods that add their own wrenches use the BuildCraft API if it's available. This allows me to easily integration with BuildCraft compatible wrenches.
- Other tech mods like IC2 and Forestry will require custom handling on my part.

**Comment by vladmarica** [comment]
More mod support may be added in the future, for now this is enough.
